ALTER TABLE `franchisee` 
ADD COLUMN `EIN` VARCHAR(45) NULL DEFAULT NULL,
ADD COLUMN `LegalEntity` VARCHAR(45) NULL DEFAULT NULL , 
ADD COLUMN `RenewalFee` DECIMAL(10,2) NULL DEFAULT NULL,
ADD COLUMN `DateOfRenewal` DATE NULL DEFAULT NULL,
ADD COLUMN `Description` VARCHAR(512) NULL DEFAULT NULL,
ADD COLUMN `TransferFee` DECIMAL(10,2) NULL DEFAULT NULL,
ADD COLUMN `OriginalFranchiseeFee` DECIMAL(10,2) NULL DEFAULT NULL;

UPDATE `servicetype` SET `Name`='MLFS-FRANCHISE SALES' WHERE `Id`='21';

