CREATE TABLE `Auditaddress` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `TypeId` bigint(20) NOT NULL,
  `AddressLine1` varchar(512) NOT NULL,
  `AddressLine2` varchar(512) DEFAULT NULL,
  `CityId` bigint(20) DEFAULT NULL,
  `StateId` bigint(20) DEFAULT NULL,
  `CountryId` bigint(20) NOT NULL,
  `ZipId` bigint(20) DEFAULT NULL,
  `CityName` varchar(512) DEFAULT NULL,
  `ZipCode` varchar(128) DEFAULT NULL,
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
  `StateName` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_Auditaddress_Lookup2_idx` (`TypeId`),
  KEY `fk_Auditaddress_City2_idx` (`CityId`),
  KEY `fk_Auditaddress_State2_idx` (`StateId`),
  KEY `fk_Auditaddress_Zip2_idx` (`ZipId`),
  KEY `fk_Auditaddress_Country1_idx` (`CountryId`),
  CONSTRAINT `fk_Auditaddress_City2` FOREIGN KEY (`CityId`) REFERENCES `city` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auditaddress_Country2` FOREIGN KEY (`CountryId`) REFERENCES `country` (`Id`),
  CONSTRAINT `fk_Auditaddress_Lookup2` FOREIGN KEY (`TypeId`) REFERENCES `lookup` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auditaddress_State2` FOREIGN KEY (`StateId`) REFERENCES `state` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auditaddress_Zip2` FOREIGN KEY (`ZipId`) REFERENCES `zip` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=659599 DEFAULT CHARSET=latin1