CREATE TABLE `auditfranchiseesales` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `FranchiseeId` bigint(20) DEFAULT NULL,
  `CustomerId` bigint(20) DEFAULT NULL,
  `InvoiceId` bigint(20) DEFAULT NULL,
  `ClassTypeId` bigint(20) DEFAULT NULL,
  `SalesRep` varchar(5) DEFAULT NULL,
  `Amount` decimal(10,2) DEFAULT NULL,
  `QbInvoiceNumber` varchar(16) DEFAULT NULL,
  `annualsalesdatauploadId` bigint(20) DEFAULT NULL,
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
  `CurrencyExchangeRateId` bigint(20) DEFAULT NULL,
  `AccountCreditId` bigint(20) DEFAULT NULL,
  `addressId` bigint(20) DEFAULT NULL,
  `AuditCustomerId` bigint(20) DEFAULT NULL,
  `AuditInvoiceId` bigint(20) DEFAULT NULL,
   PRIMARY KEY (`Id`),
  KEY `fk_auditfranchiseesales_Invoice2_idx` (`InvoiceId`),
  KEY `fk_auditfranchiseesales_Customer2_idx` (`CustomerId`),
  KEY `fk_auditfranchiseesales_franchisee2_idx` (`FranchiseeId`),
  KEY `fk_auditfranchiseesales_MarketingClass2_idx` (`ClassTypeId`),
  KEY `fk_auditfranchiseesales_AccountCredit2_idx` (`AccountCreditId`),
  KEY `fk_auditfranchiseesales_AuditAddress2_idx` (`addressId`),

  CONSTRAINT `fk_auditfranchiseesales_AccountCredit1` FOREIGN KEY (`AccountCreditId`) REFERENCES `accountcredit` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_Customer1` FOREIGN KEY (`CustomerId`) REFERENCES `customer` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_Invoice1` FOREIGN KEY (`InvoiceId`) REFERENCES `invoice` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_MarketingClass1` FOREIGN KEY (`ClassTypeId`) REFERENCES `marketingclass` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_annualsalesdataupload` FOREIGN KEY (`annualsalesdatauploadId`) REFERENCES `annualsalesdataupload` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_franchisee1` FOREIGN KEY (`FranchiseeId`) REFERENCES `franchisee` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditfranchiseesales_auditinvoice` FOREIGN KEY (`AuditInvoiceId`) REFERENCES `auditinvoice` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=106167 DEFAULT CHARSET=utf8
