INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('1', 'Type6', 'Split Invoices After Report', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('2', 'Type1C', 'Added Work Unreport', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('3', 'Type5', 'Missing Prior Reported Job', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('4', 'Tyoe 1B', 'Missing Job Unreport', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('5', 'Type 1A', 'Cash Payments Unreport', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('6', 'Type 14', 'Add;Work Added to Invoice After Weekly', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('7', 'Type 4', 'DUP Payment Entry', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('8', 'Type 1F', '2ND Payment Missing From Weekly', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('9', 'Type 1D', 'Missing Invoice And Payment Unreport', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('10', 'Type 3', 'Check for Job Completion', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('11', 'Type 2A', 'Audit Entry- Payment Unrepor', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('12', 'Type 2B', 'Audit Entry Matching Errors', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('13', 'Type 7', 'Invoice Changed Between Weekly and Annually', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`,`Description`, `IsDeleted`) VALUES  ('14', 'Type 8','Missing Sales Tax', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('15', 'Type 9', 'Rounding', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('16', 'Type 10B', 'Missing Invoice But Payment Posted', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('17', 'Type 11', 'Salestax Not Classed-Corrected', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('18', 'Type 12', 'Blank', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('19', 'Type 13', 'Split Incoice-Weekly Payment Exceeds Weekly', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('20', 'Type 13B', 'Invoice Split- Weekly and Annual ', b'0');
INSERT INTO `annualreporttype` (`Id`, `ReportTypeName`, `Description`, `IsDeleted`) VALUES ('21', 'Type 16', 'Payment Reduced in Annual', b'0');
