CREATE TABLE `invoiceAddress` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT ,
  `InvoiceId` bigint(20) DEFAULT NULL,
  `TypeId` bigint(20) NOT NULL,
  `AddressLine1` varchar(512) NOT NULL,
  `AddressLine2` varchar(512) DEFAULT NULL,
  `CityId` bigint(20) DEFAULT NULL,
  `StateId` bigint(20) DEFAULT NULL,
  `CountryId` bigint(20) NOT NULL,
  `ZipId` bigint(20) DEFAULT NULL,
  `CityName` varchar(512) DEFAULT NULL,
  `ZipCode` varchar(128) DEFAULT NULL,
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
  `StateName` varchar(512) DEFAULT NULL,
  `emailId` varchar(512) DEFAULT NULL,
  `Phone` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_invoiceAddress_invoice_idx` (`InvoiceId`),
  KEY `fk_invoiceAddress_Lookup1_idx` (`TypeId`),
  KEY `fk_invoiceAddress_City1_idx` (`CityId`),
  KEY `fk_invoiceAddress_State1_idx` (`StateId`),
  KEY `fk_invoiceAddress_Zip1_idx` (`ZipId`),
  KEY `fk_invoiceAddress_Country1_idx` (`CountryId`),
  CONSTRAINT `fk_invoiceAddress_invoice` FOREIGN KEY (`InvoiceId`) REFERENCES `invoice` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT `fk_invoiceAddress_Lookup1` FOREIGN KEY (`TypeId`) REFERENCES `lookup` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoiceAddress_City1` FOREIGN KEY (`CityId`) REFERENCES `city` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoiceAddress_Country1` FOREIGN KEY (`CountryId`) REFERENCES `country` (`Id`),
  CONSTRAINT `fk_invoiceAddress_State1` FOREIGN KEY (`StateId`) REFERENCES `state` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoiceAddress_Zip1` FOREIGN KEY (`ZipId`) REFERENCES `zip` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1