CREATE TABLE `jobDetails` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `JobTypeId` bigint(20) NOT NULL,
  `QBInvoiceNumber` varchar(45) DEFAULT NULL,
  `Description` varchar(1024) DEFAULT NULL,
  `CustomerId` bigint(20) NOT NULL,
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
  `StatusId` bigint(20) NOT NULL,
  `StartDate` datetime NOT NULL,
  `EndDate` datetime NOT NULL,
  `EstimateId` bigint(20) DEFAULT NULL,
  `GeoCode` varchar(128) DEFAULT NULL,
  `EndDateTimeString` datetime NOT NULL,
  `StartDateTimeString` datetime NOT NULL,
  `Offset` double DEFAULT NULL,
   `SchedulerId` bigint(20) NOT NULL,
   `JobId` bigint(20) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_jobDetails_jobType_idx` (`JobTypeId`),
  KEY `fk_jobDetails_jobCustomer_idx` (`CustomerId`),
  KEY `fk_jobDetails_jobStatus_idx` (`StatusId`),
  KEY `fk_jobDetails_jobEstimate_idx` (`EstimateId`),
  KEY `fk_jobDetails_jobScheduler_idx` (`SchedulerId`),
   KEY `fk_jobDetails_job_idx` (`JobId`),
  CONSTRAINT `fk_jobDetails_jobCustomer` FOREIGN KEY (`CustomerId`) REFERENCES `jobcustomer` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobDetails_jobEstimate` FOREIGN KEY (`EstimateId`) REFERENCES `jobestimate` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobDetails_jobStatus` FOREIGN KEY (`StatusId`) REFERENCES `jobstatus` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobDetails_jobType` FOREIGN KEY (`JobTypeId`) REFERENCES `marketingclass` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobDetails_jobscheduler` FOREIGN KEY (`SchedulerId`) REFERENCES `jobscheduler` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobDetails_job` FOREIGN KEY (`JobId`) REFERENCES `job` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1772 DEFAULT CHARSET=latin1