UPDATE `makalu`.`emailtemplate` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '1');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '2');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Invoice Notification' WHERE (`Id` = '3');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Payment Reminder' WHERE (`Id` = '4');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Sales Data Upload Reminder' WHERE (`Id` = '5');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Payment Late Fee' WHERE (`Id` = '6');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Payment Confirmation' WHERE (`Id` = '7');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Sales Data Upload Latefee' WHERE (`Id` = '8');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Weekly Late Fee Notification' WHERE (`Id` = '9');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Weekly Unpaid Invoice Notification' WHERE (`Id` = '10');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER - Feedback' WHERE (`Id` = '11');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CORPORATE - Monthly Customer List' WHERE (`Id` = '12');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'OWNER - Monthly Review System Notification' WHERE (`Id` = '13');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CORPORATE - Monthly Mailchimp Report' WHERE (`Id` = '14');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'ACCOUNTING - Monthly Sales Upload Notification' WHERE (`Id` = '15');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '21');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'USER - Document Upload' WHERE (`Id` = '22');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'Owner - Document Expiry' WHERE (`Id` = '23');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'Owner - Document Upload to Franchisee' WHERE (`Id` = '24');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER - Job Scheduled Confirmation' WHERE (`Id` = '30');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'TECH - New Job Assignment' WHERE (`Id` = '26');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER - Job Scheduled Confirmation' WHERE (`Id` = '25');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'TECH - Job Cancelation' WHERE (`Id` = '27');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'TECH - Job Update' WHERE (`Id` = '28');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER - Post Service REVIEW Request, Care Product Communication' WHERE (`Id` = '29');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'SALES/TECH - Job-Estimate REASSIGNED' WHERE (`Id` = '31');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'TECH - Urgent Job Update' WHERE (`Id` = '32');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CORP ACCOUNTING - AR Report' WHERE (`Id` = '33');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CORP ACCOUNTING - Loan Completion' WHERE (`Id` = '36');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER-New Job Scheduled' WHERE (`Id` = '37');
UPDATE `makalu`.`emailtemplate` SET `Title` = 'CUSTOMER-Job Schedule Update' WHERE (`Id` = '38');

UPDATE `makalu`.`notificationtype` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '1');
UPDATE `makalu`.`notificationtype` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '2');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Invoice Notification' WHERE (`Id` = '3');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Payment Reminder' WHERE (`Id` = '4');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Sales Data Upload Reminder' WHERE (`Id` = '5');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Payment Late Fee' WHERE (`Id` = '6');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Payment Confirmation' WHERE (`Id` = '7');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Sales Data Upload Latefee' WHERE (`Id` = '8');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Weekly Late Fee Notification' WHERE (`Id` = '9');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Weekly Unpaid Invoice Notification' WHERE (`Id` = '10');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CUSTOMER - Feedback' WHERE (`Id` = '11');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CORPORATE - Monthly Customer List' WHERE (`Id` = '12');
UPDATE `makalu`.`notificationtype` SET `Title` = 'OWNER - Monthly Review System Notification' WHERE (`Id` = '13');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CORPORATE - Monthly Mailchimp Report' WHERE (`Id` = '14');
UPDATE `makalu`.`notificationtype` SET `Title` = 'ACCOUNTING - Monthly Sales Upload Notification' WHERE (`Id` = '15');
UPDATE `makalu`.`notificationtype` SET `Title` = 'USER - Login Credential' WHERE (`Id` = '21');
UPDATE `makalu`.`notificationtype` SET `Title` = 'USER - Document Upload' WHERE (`Id` = '22');
UPDATE `makalu`.`notificationtype` SET `Title` = 'Owner - Document Expiry' WHERE (`Id` = '23');
UPDATE `makalu`.`notificationtype` SET `Title` = 'Owner - Document Upload to Franchisee' WHERE (`Id` = '24');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CUSTOMER - Job Scheduled Confirmation' WHERE (`Id` = '25');
UPDATE `makalu`.`notificationtype` SET `Title` = 'TECH - New Job Assignment' WHERE (`Id` = '26');
UPDATE `makalu`.`notificationtype` SET `Title` = 'TECH - Job Cancelation' WHERE (`Id` = '27');
UPDATE `makalu`.`notificationtype` SET `Title` = 'TECH - Job Update' WHERE (`Id` = '28');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CUSTOMER - Post Service REVIEW Request, Care Product Communication' WHERE (`Id` = '29');
UPDATE `makalu`.`notificationtype` SET `Title` = 'SALES/TECH - Job-Estimate REASSIGNED' WHERE (`Id` = '31');
UPDATE `makalu`.`notificationtype` SET `Title` = 'TECH - Urgent Job Update' WHERE (`Id` = '32');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CORP ACCOUNTING - AR Report' WHERE (`Id` = '33');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CORP ACCOUNTING - Loan Completion' WHERE (`Id` = '36');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CUSTOMER-New Job Scheduled' WHERE (`Id` = '37');
UPDATE `makalu`.`notificationtype` SET `Title` = 'CUSTOMER-Job Schedule Update' WHERE (`Id` = '38');


INSERT INTO `makalu`.`lookup` (`Id`, `LookupTypeId`, `Name`, `Alias`, `RelativeOrder`, `IsActive`, `IsDeleted`) VALUES ('230', '9', '$0-DUE', '$0-DUE', '4', b'1', b'0');



UPDATE `makalu`.`emailtemplate` SET `Subject` = 'USER - Login Credential | @Model.Franchisee' WHERE (`Id` = '1');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'USER - Login Credentiall | @Model.Franchisee' WHERE (`Id` = '2');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Invoice Notification | @Model.Franchisee' WHERE (`Id` = '3');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Payment Reminder | @Model.Franchisee' WHERE (`Id` = '4');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Sales Data Upload Reminder | @Model.Franchisee' WHERE (`Id` = '5');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Payment Late Fee | @Model.Franchisee' WHERE (`Id` = '6');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Payment Confirmation| @Model.Franchisee' WHERE (`Id` = '7');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Sales Data Upload Latefee | @Model.Franchisee' WHERE (`Id` = '8');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Weekly Late Fee Notification' WHERE (`Id` = '9');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Weekly Unpaid Invoice Notification' WHERE (`Id` = '10');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CORPORATE - Monthly Customer List' WHERE (`Id` = '12');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'OWNER - Monthly Review System Notification | @Model.Franchisee' WHERE (`Id` = '13');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CORPORATE - Monthly Mailchimp Report' WHERE (`Id` = '14');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'ACCOUNTING - Monthly Sales Upload Notification' WHERE (`Id` = '15');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'USER - Login Credential | @Model.Franchisee' WHERE (`Id` = '21');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'USER - Document Upload | @Model.Franchisee' WHERE (`Id` = '22');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'Owner - Document Expiry | @Model.Franchisee' WHERE (`Id` = '23');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'Owner - Document Upload to Franchisee | @Model.Franchisee' WHERE (`Id` = '24');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CUSTOMER - Job  @Model.jobType Scheduled Confirmation' WHERE (`Id` = '25');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CORP ACCOUNTING - AR Report' WHERE (`Id` = '33');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CUSTOMER-New Job @Model.jobType Scheduled' WHERE (`Id` = '37');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CUSTOMER- @Model.jobType Schedule Update' WHERE (`Id` = '38');
UPDATE `makalu`.`emailtemplate` SET `Subject` = 'CUSTOMER-New @Model.jobType Scheduled' WHERE (`Id` = '37');
