CREATE TABLE `BeforeAfterImages` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `JobId` bigint(20) DEFAULT NULL,
  `EstimateId` bigint(20) DEFAULT NULL,
  `MarkertingClassId` bigint(20) DEFAULT NULL,
  `SchedulerId` bigint(20) DEFAULT NULL,
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
 
  `CategoryId` bigint(20) DEFAULT NULL,
  `SurfaceColor` varchar(512) DEFAULT NULL,
  `FinishMaterial` varchar(512) DEFAULT NULL,
  `SurfaceMaterial` varchar(512) DEFAULT NULL,
  `SurfaceType` varchar(512) DEFAULT NULL,
  `DataRecorderMetaDataId` bigint(20) DEFAULT NULL,
  `PairId` bigint(20) DEFAULT NULL,
  `BuildingLocation` varchar(512) DEFAULT NULL,
  `ServiceTypeId` bigint(20) DEFAULT NULL,
  `description` varchar(1024) DEFAULT NULL,
  `IsBeforeImage` bit(1) DEFAULT NULL,
  `CompanyName` varchar(220) DEFAULT NULL,
  `MaidService` varchar(220) DEFAULT NULL,
  `PropertyManager` varchar(220) DEFAULT NULL,
  `MAIDJANITORIAL` varchar(220) DEFAULT NULL,
  `FloorNumber` int(20) DEFAULT '0',
  
  `ServiceId` bigint(20) DEFAULT NULL,
  `FileId` bigint(20) DEFAULT NULL,
  `TypeId` bigint(20) DEFAULT NULL,
  `IsBestImage` bigint(20) DEFAULT '0',
  `BestFitMarkDateTime` datetime DEFAULT NULL,
  `AddToGalleryDateTime` datetime DEFAULT NULL,
  `IsAddToLocalGallery` bigint(20) DEFAULT '0',
  `PersonName` varchar(220) DEFAULT NULL,
  `FranchiseeId` bigint(20) DEFAULT NULL,
  `RoleId` bigint(20) DEFAULT NULL,
  `UserId` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_beforeAfte_jobEstimateimageCategory_idx` (`CategoryId`),
  KEY `fk_beforeAfte_PairId_idx` (`PairId`),
  KEY `fk_beforeAfter_servicetype` (`ServiceTypeId`),
  KEY `fk_beforeAfte_Lookup_idx` (`TypeId`),
  KEY `fk_beforeAfte_file_idx` (`FileId`),
  KEY `fk_beforeAfte_jobEstimateServices_idx` (`ServiceId`),
  KEY `fk_beforeAfte_dataRecorderMetaData_idx` (`DataRecorderMetaDataId`),
   KEY `fk_beforeAfte_job_idx` (`JobId`),
  KEY `fk_beforeAfte_estimate_idx` (`EstimateId`),
  KEY `fk_beforeAfte_marketingclass_idx` (`MarkertingClassId`),
  KEY `fk_beforeAfte_jobScheduler_idx` (`SchedulerId`),
   KEY `fk_beforeAfte_frachisee_idx` (`FranchiseeId`),
   KEY `fk_beforeAfte_role_idx` (`RoleId`),
   KEY `fk_beforeAfte_person_idx` (`UserId`),

  CONSTRAINT `fk_beforeAfter_servicetype` FOREIGN KEY (`ServiceTypeId`) REFERENCES `servicetype` (`Id`),
  CONSTRAINT `fk_beforeAfte_CategoryId` FOREIGN KEY (`CategoryId`) REFERENCES `jobestimateimagecategory` (`Id`),
  CONSTRAINT `fk_beforeAfte_PairId` FOREIGN KEY (`PairId`) REFERENCES `jobestimateservices` (`Id`),
  CONSTRAINT `fk_beforeAfte_Lookup` FOREIGN KEY (`TypeId`) REFERENCES `lookup` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_file` FOREIGN KEY (`FileId`) REFERENCES `file` (`Id`),
  CONSTRAINT `fk_beforeAfte_servicetype` FOREIGN KEY (`ServiceId`) REFERENCES `jobestimateservices` (`Id`),
  CONSTRAINT `fk_beforeAfte_dataRecorderMetaData` FOREIGN KEY (`DataRecorderMetaDataId`) REFERENCES `datarecordermetadata` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_estimate` FOREIGN KEY (`EstimateId`) REFERENCES `jobscheduler` (`EstimateId`),
  CONSTRAINT `fk_beforeAfte_job` FOREIGN KEY (`JobId`) REFERENCES `jobscheduler` (`JobId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_jobScheduler1` FOREIGN KEY (`SchedulerId`) REFERENCES `jobscheduler` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_marketingclass` FOREIGN KEY (`MarkertingClassId`) REFERENCES `marketingclass` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_frachisee` FOREIGN KEY (`FranchiseeId`) REFERENCES `franchisee` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_role` FOREIGN KEY (`RoleId`) REFERENCES `role` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_beforeAfte_person` FOREIGN KEY (`UserId`) REFERENCES `person` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION
  
 
);
