insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (969,11,285,'Slate','Hone',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (970,11,282,'Slate','Cleanshield',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (971,11,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (972,6,286,'Slate','Maintenance (Monthly)',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (973,7,286,'Slate','Maintenance (Bi-Monthly)',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (974,8,286,'Slate','Maintenance (Quarterly)',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (975,42,286,'Slate','Maintenance (Other Frequency)',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (976,3,282,'Slate','Stripping Carpet Adhesive',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (977,3,282,'Slate','Stripping-Silicone',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (978,3,282,'Slate','Stripping-Urethane',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (979,3,282,'Slate','Stripping-Wax',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (980,3,282,'Slate','Stripping-Unknown',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (981,3,283,'Slate','Grout Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (982,3,283,'Slate','Grout Replacement',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (983,3,284,'Slate','Tile Replacement',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (984,3,282,'Slate','Colorseal-Hydroforce',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (985,3,282,'Slate','Colorseal-Powerwash',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (986,3,282,'Slate','Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (987,3,282,'Slate','Powerwash Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (988,3,282,'Slate','Hydroforce Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (989,3,284,'Slate','Tile Rebond',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (990,3,283,'Slate','Caulking',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (991,3,282,'Slate','Tilelok',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (992,3,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (993,38,284,'Slate','Concrete Chip Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (994,38,284,'Slate','Concrete Crack Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (995,38,284,'Slate','Large Concrete Area Repairs',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (996,38,284,'Slate','Terrazzo Chip Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (997,38,284,'Slate','Terrazzo Crack Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (998,38,284,'Slate','Terrazzo Large Area Repair',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (999,38,283,'Slate','Expansion Joint Repairs',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1000,38,283,'Slate','Expansion Joint Sealing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1001,38,282,'Slate','Stripping Carpet Adhesive',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1002,38,282,'Slate','Stripping-Silicone',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1003,38,282,'Slate','Stripping-Urethane',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1004,38,282,'Slate','Stripping-Wax',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1005,38,282,'Slate','Stripping-Unknown',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1006,38,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1007,2,285,'Slate','Honing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1008,2,282,'Slate','Densification',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1009,2,285,'Slate','Polishing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1010,2,282,'Slate','Guard',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1011,2,282,'Slate','Concrete Stain Application',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1012,2,284,'Slate','Concrete Spot Stain Removal',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1013,2,282,'Slate','Concrete Microtopping Overlayment',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1014,2,282,'Slate','Sealing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1015,2,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1016,33,282,'Slate','Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1017,33,282,'Slate','Powerwash - Mold Stain Removal',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1018,33,285,'Slate','Hone Surface Prep',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1019,33,282,'Slate','Moisture Vapor Barrier',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1020,33,282,'Slate','Epoxy Base',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1021,33,282,'Slate','Polyspartic Base',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1022,33,282,'Slate','Vinyl Chips',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1023,33,282,'Slate','Epoxy Top Coat',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1024,33,282,'Slate','Polyspartic Top Coat',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1025,33,284,'Slate','Endurachip - Light',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1026,33,284,'Slate','Endurachip - Fast',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1027,33,282,'Slate','Endurachip - Durable',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1028,33,282,'Slate','MARBLIZED COATING',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1029,33,282,'Slate','Anti-Spauling Driveway Sealing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1030,33,282,'Slate','Anti-Spauling Sideway Sealing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1031,33,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1032,34,282,'Slate','Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1033,34,282,'Slate','Overlayment Installation',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1034,34,282,'Slate','Marblized Top Coat Installation',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1035,35,285,'Slate','Concrete Preparations',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1036,35,282,'Slate','Cooldeck Overlayment',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1037,35,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1038,16,282,'Slate','Carpet Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1039,16,282,'Slate','Carpet Guard',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1040,16,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1041,13,282,'Slate','Clean Air Purification Treatments',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1042,13,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1043,15,282,'Slate','Metal Stripping',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1044,15,282,'Slate','Metal Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1045,15,285,'Slate','Metal Scratch Removal',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1046,15,282,'Slate','Metal Laquer, Sealing & Protection',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1047,15,284,'Slate','Other',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1048,17,284,'Slate','Tile Removal',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1049,17,282,'Slate','Tile Installation',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1050,17,282,'Slate','Grouting',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1051,17,282,'Slate','Grout Haze Removal',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1052,17,282,'Slate','Grout Sealing - Clear',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1053,17,282,'Slate','Grout & Tile Sealing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1054,4,282,'Slate','Stripping Wax',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1055,4,282,'Slate','Waxing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1056,4,282,'Slate','Cleaning and Pre-Coat Preparations',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1057,4,282,'Slate','VinylGuard Installation',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1058,40,282,'Slate','Cleaning',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1059,40,282,'Slate','Scuffing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1060,40,282,'Slate','Re-Coat',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1061,40,282,'Slate','Buffing',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1062,40,285,'Slate','Scratch & Wear Removal (Sanding)',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1063,40,282,'Slate','Staining',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1064,40,282,'Slate','Top Coat',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1065,18,287,'Slate','Granite Cleaner 32 oz Spray',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1066,18,287,'Slate','Granite Cleaner Refill Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1067,18,287,'Slate','Granite Gloss conditioner 8oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1068,18,287,'Slate','Granite Sealer 4 oz Spray',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1069,18,287,'Slate','Marble Cleaner 32 oz Spray',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1070,18,287,'Slate','Marble cleaner Refill Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1071,18,287,'Slate','Marble cleaner Conc. 32oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1072,18,287,'Slate','Marble Polish 16 oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1073,18,287,'Slate','Marble Gloss conditioner 16oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1074,18,287,'Slate','Stone Sealer 16 oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1075,18,287,'Slate','Tile Cleaner 32oz Spray',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1076,18,287,'Slate','Tile Cleaner Refill Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1077,18,287,'Slate','Tile Cleaner Concentrate 32 oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1078,18,287,'Slate','MaxOut Grout Cleaner 32 oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1079,18,287,'Slate','MaxOut Concentrate Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1080,18,287,'Slate','Grout Sealer 16 oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1081,18,287,'Slate','Floor Cleaner Concentrate Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1082,18,287,'Slate','Mold & Mildew Stain Remover 32oz Spray',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1083,18,287,'Slate','Mold & Mildew Stain Remover Gallon',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1084,18,287,'Slate','Soap Scum Remover 16oz',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1085,19,288,'Slate','Service',b'0');
insert into servicestag(Id, ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted) values (1086,19,288,'Slate','Products',b'0');


insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (Null,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (3,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (4,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (5,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (6,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (8,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (9,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (10,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (11,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (14,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (15,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (16,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (17,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (18,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (19,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (20,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (21,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (22,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (23,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (25,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (27,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (29,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (30,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (31,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (38,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (39,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (40,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (41,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (42,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (45,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (46,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (47,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (48,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (50,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (51,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (52,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (53,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (54,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (56,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (57,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (61,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (62,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (64,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (70,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (72,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (74,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (75,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (76,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (77,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (78,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (79,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (80,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (81,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (82,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (83,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (84,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (85,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (86,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (87,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (88,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (90,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (91,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (92,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (93,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (94,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');
insert into maintenancecharges(FranchiseeId,Material, UOM, IsPriceChangedByFranchisee, IsActive, IsDeleted) values (95,'Slate','Sqft/Tech Shift',b'0',b'1',b'0');

update maintenancecharges 
set `Order` = 8 where material = 'Slate' and Id >0;

insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (Null,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (3,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (4,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (5,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (6,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (8,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (9,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (10,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (11,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (14,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (15,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (16,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (17,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (18,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (19,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (20,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (21,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (22,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (23,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (25,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (27,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (29,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (30,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (31,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (38,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (39,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (40,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (41,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (42,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (45,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (46,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (47,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (48,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (50,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (51,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (52,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (53,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (54,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (56,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (57,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (61,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (62,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (64,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (70,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (72,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (74,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (75,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (76,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (77,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (78,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (79,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (80,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (81,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (82,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (83,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (84,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (85,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (86,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (87,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (88,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (90,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (91,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (92,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (93,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (94,'Slate',b'0',b'1',b'0');
insert into replacementcharges(FranchiseeId,Material,IsPriceChangedByFranchisee, IsActive, IsDeleted) values (95,'Slate',b'0',b'1',b'0');

update replacementcharges 
set `Order` = 8 where material = 'Slate' and Id >0;



UPDATE `makalu`.`emailtemplate` SET `Body` = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n    <html xmlns=\"http://www.w3.org/1999/xhtml\">\n    	<head>\n    		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n    		<title>@Model.Base.CompanyName</title>\n    		<style type=\"text/css\">\n    			body {\n                    padding-left: 10px !important;\n                    padding-right: 10px !important;\n                    padding-top: 10px !important;\n                    padding-bottom: 10px !important;\n                    margin: 20px !important;\n                    width: 600px;\n                    border: solid 1px #B2C8D9;\n                    -webkit-text-size-adjust: 100% !important;\n                    -ms-text-size-adjust: 100% !important;\n                    -webkit-font-smoothing: antialiased !important;\n                    font-size: 16px;\n                }\n                a {\n                    color: #382F2E;\n                }\n                p, h1 {\n                    margin: 0;\n                }\n                p {\n                    text-align: left;\n                    font-weight: normal;\n                    line-height: 19px;\n                }\n                a.link1 {\n                    color: #382F2E;\n                }\n                a.link2 {\n                    text-decoration: none;\n                    color: #ffffff;\n                }\n                h2 {\n                    text-align: left;\n                    color: #222222;\n                    font-size: 19px;\n                    font-weight: normal;\n                }\n                div, p, ul, h1 {\n                    margin: 0;\n                }\n                .bgBody {\n    				background: #ffffff;\n    			}\n                table thead tr th {\n                    border: 1px solid black;\n                    padding: 5px;\n                    margin: 2px;\n                    text-align: left;\n                }\n                table tbody tr td {\n                    border: 1px solid black;\n                    padding: 5px;\n                    margin: 2px;\n                    text-align: left;\n                }\n                .block\n                {\n                    display:block;\n                }\n                .none\n                {\n                display:none;\n                }\n                .btn-confirm\n                {\n    				background-color:#26327e !important;\n    				margin-left:30% !important;\n    				color: white!important;\n    				border:none !important;\n    				width:40% !important;\n    				margin-top:5% !important;\n    				height:42px !important;\n                }\n                .btn-cancel\n                {\n                    background-color:#26327e !important;\n                    margin-left:30% !important;\n                    color: white!important;\n                    border:none !important;\n                    width:38% !important;\n                    margin-top:5% !important;\n                    height:42px !important;\n    			}\n            </style>\n        </head>\n        <body style=\"background-repeat: repeat; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased;\">\n    		<div class=\"contentEditableContainer contentTextEditable\">\n    			<div class=\"contentEditable\">\n                    <span>Dear @Model.CustomerName,</span>\n                    <br /><br />   \n                    <p>\n                    Once again, THANK YOU, for the opportunity to assist you with the restoration-and-maintenance of your building surfaces.\n    				<br/><br/>\n    				@Model.InvoicesName\n    				<br/><br/> \n                 <div class =\"@Model.AllInvoicesNotSigned\">\n    				Assuming this meets your approval, we can consider that our Technician can start his Job for the Invoice(s) signed.\n    				</div>\n                 <br/><br/>\n                      <div class=\"@Model.AllInvoicesSigned\">\n    						Please review the Invoice attached in the mail.\n    					</div>\n   					<div class =\"@Model.AllInvoicesNotSigned\">\n    						Please review the Invoice attached in the mail and <a href=@Model.Url>Click here</a> to sign the unsigned Invoices if you change your mind in the future. Please use 5 digit code @Model.Code to verify your account.\n    					</div>\n    					<br/>\n    					@Model.InvoicesSignedBy\n             		<br/><br/>\n    				We look forward to working with you.							\n                    </p>\n                    <br /><br/><br/>\n    				Regards,\n                    <p>\n                      @Model.Base.CompanyName<sup>&reg;</sup> <br />\n                      @Model.AssigneePhone <br />\n                    </p>\n    			</div>\n            </div>\n        </body>\n    </html>' WHERE (`Id` = '571');
