insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Stripping Carpet Adhesive',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Stripping-Silicone',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Stripping-Urethane',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Stripping-Wax',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Stripping-Unknown',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Chip Repair',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Crack Repair',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Tile Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,283,'Quartz','Grout Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Hard Water Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Mold Stain Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Traverfil',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Sealing',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Stain Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,283,'Quartz','Caulking',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,282,'Quartz','Coating',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (1,284,'Quartz','Other',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,282,'Quartz','Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Chip Repair',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Crack Repair',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Tile Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,283,'Quartz','Grout Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Hard Water Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,282,'Quartz','Mold Stain Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,282,'Quartz','Sealing',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Stain Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,283,'Quartz','Caulking',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,282,'Quartz','Coating',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (5,284,'Quartz','Other',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (11,282,'Quartz','Cleanshield',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (11,284,'Quartz','Other',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Stripping Carpet Adhesive',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Stripping-Silicone',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Stripping-Urethane',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Stripping-Wax',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Stripping-Unknown',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,283,'Quartz','Grout Repair',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,283,'Quartz','Grout Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,284,'Quartz','Tile Replacement',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Colorseal-Hydroforce',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Colorseal-Powerwash',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Powerwash Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,282,'Quartz','Hydroforce Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,284,'Quartz','Tile Rebond',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (3,283,'Quartz','Caulking',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (33,282,'Quartz','Powerwash - Mold Stain Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (33,282,'Quartz','Epoxy Base',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (33,282,'Quartz','Epoxy Top Coat',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (33,282,'Quartz','Endurachip - Durable',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (33,284,'Quartz','Other',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (34,282,'Quartz','Cleaning',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (34,282,'Quartz','Overlayment Installation',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (34,282,'Quartz','Marblized Top Coat Installation',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (35,282,'Quartz','Cooldeck Overlayment',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (35,284,'Quartz','Other',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,284,'Quartz','Tile Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,282,'Quartz','Tile Installation',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,282,'Quartz','Grouting',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,282,'Quartz','Grout Haze Removal',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,282,'Quartz','Grout Sealing - Clear',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (17,282,'Quartz','Grout & Tile Sealing',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (4,282,'Quartz','Stripping Wax',b'1',b'0');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsActive, IsDeleted) values (4,282,'Quartz','Waxing',b'1',b'0');
