CREATE TABLE `honingmeasurementDefault` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `EstimateInvoiceServiceId` bigint(20) DEFAULT NULL,
  `HoningMeasurementId` bigint(20) DEFAULT NULL,
  `SectionsDefault` decimal(18,2) DEFAULT NULL,
  `UGCDefault` decimal(18,2) DEFAULT NULL,
  `ThirtyDefault` decimal(18,2) DEFAULT NULL,
  `FiftyDefault` decimal(18,2) DEFAULT NULL,
  `HundredDefault` decimal(18,2) DEFAULT NULL,
  `TwoHundredDefault` decimal(18,2) DEFAULT NULL,
  `FourHundredDefault` decimal(18,2) DEFAULT NULL,
  `EightHundredDefault` decimal(18,2) DEFAULT NULL,
  `FifteenHundredDefault` decimal(18,2) DEFAULT NULL,
  `ThreeThousandDefault` decimal(18,2) DEFAULT NULL,
  `EightThousandDefault` decimal(18,2) DEFAULT NULL,
  `ElevenThousandDefault` decimal(18,2) DEFAULT NULL,
  `CacoDefault` decimal(18,2) DEFAULT NULL,
  `IhgDefault` decimal(18,2) DEFAULT NULL,
  `DimensionDefault` decimal(18,2) DEFAULT NULL,
  `ProdutivityRateDefault` decimal(18,2) DEFAULT NULL,
  `TotalAreaInHourDefault` decimal(18,2) DEFAULT NULL,
  `TotalAreaInShiftDefault` decimal(18,2) DEFAULT NULL,
  `TotalMinuteDefault` decimal(18,2) DEFAULT NULL,
  `TotalAreaDefault` decimal(18,2) DEFAULT NULL,
  `TotalCostDefault` decimal(18,2) DEFAULT NULL,
  `TotalCostPerSquareDefault` decimal(18,2) DEFAULT NULL,
  `MinRestorationDefault` decimal(18,2) DEFAULT NULL,
  `SeventeenBaseDefault` decimal(18,2) DEFAULT NULL,
  `IsDeleted` bit(1) DEFAULT b'0',
  `IsActive` bit(1) DEFAULT b'0',
  PRIMARY KEY (`Id`),
  KEY `fk_honingMeasurementDefault_estimateInvoice_idx` (`EstimateInvoiceServiceId`),
  KEY `HoningMeasurementId` (`HoningMeasurementId`),
  CONSTRAINT `fk_honingMeasurementDefault_estimateInvoice` FOREIGN KEY (`EstimateInvoiceServiceId`) REFERENCES `estimateinvoiceservice` (`ID`),
  CONSTRAINT `honingmeasurementDefault_ibfk_1` FOREIGN KEY (`HoningMeasurementId`) REFERENCES `honingmeasurement` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DELETE FROM `makalu`.`emailtemplate` WHERE (`Id` = '59');