insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Anti-Spauling Driveway Sealing',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','ACS Chips',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Base Coat (Epoxy)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Clean & Reseal',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) Epoxy - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) Epoxy - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) EPOXY - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Marblized  Marblize',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Coat Epoxy Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Coat Epoxy-Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Coat Epoxy-MVB Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Coat Epoxy-Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Coat Poly Spartic Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - ACS Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - Quartz Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - Vinyl Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Bundle Strip, Clean & Reseal',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','MVB-Base Coat (SEMIRON)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','MVB-Base Coat (Semiron-Epoxy)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Quartz Chips',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Concrete','Top Coat (Polyspartic)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Anti-Spauling Driveway Sealing',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','ACS Chips',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Base Coat (Epoxy)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Clean & Reseal',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - (Epoxy-MVB) - PolySpartic Semiron - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) Epoxy - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) Epoxy - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Epoxy Chip - Poly Sprtic (No MVB) EPOXY - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Marblized  Marblize',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Epoxy Chip - Poly Spartic MVB - Epoxy - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - MVB - Poly Spartic - Poly Spartic Semiron - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - ACS Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - Quartz Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep - Poly Spactic - Chip - Poly Spartic  - No MVB Poly Spartic - Vinyl Chip - Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Coat Epoxy Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Coat Epoxy-Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Coat Epoxy-MVB Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Coat Epoxy-Poly Spartic',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Coat Poly Spartic Only',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - ACS Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - Quartz Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Prep & Epoxy Chip -(No MVB) Epoxy - Vinyl Chip - Epoxy',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Bundle Strip, Clean & Reseal',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','MVB-Base Coat (SEMIRON)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','MVB-Base Coat (Semiron-Epoxy)',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Quartz Chips',b'0', b'1');
insert into servicestag(ServiceTypeId, CategoryId, MaterialType, Service, IsDeleted, IsActive) values (33,282,'Terrazzo','Top Coat (Polyspartic)',b'0', b'1');


alter table servicestag
Add column Notes text After Service;

alter table servicestag
Add column NotesSavedBy BigInt(20) After Notes;