using Core.Application;
using Core.Application.Attribute;
using Core.Application.Impl;
using Core.Application.ViewModel;
using Core.Notification;
using Core.Notification.Domain;
using Core.Notification.Enum;
using Core.Notification.ViewModel;
using Core.Scheduler.Domain;
using Core.Scheduler.Enum;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Core.Scheduler.Impl
{
    [DefaultImplementation]
    public class AutoGenereatedMailForBestFitNotification : IAutoGenereatedMailForBestFitNotification
    {
        private readonly INotificationService _notificationService;
        private ILogService _logService;
        private ISettings _settings;
        private IClock _clock;
        private IUnitOfWork _unitOfWork;
        private readonly IRepository<JobEstimateServices> _jobEstimateServicesRepository;
        private readonly IRepository<JobEstimateImage> _jobEstimateImageRepository;
        private readonly INotificationModelFactory _notificationModelFactory;
        private readonly IUserNotificationModelFactory _userNotificationModelFactory;
        private readonly IRepository<MarkbeforeAfterImagesHistry> _markbeforeAfterImagesHistryRepository;
        private readonly IRepository<Application.Domain.File> _fileRepository;
        private readonly IPdfFileService _pdfFileService;
        public AutoGenereatedMailForBestFitNotification(IUnitOfWork unitOfWork, ILogService logService, ISettings settings,
            IClock clock, INotificationModelFactory notificationModelFactory,
            IUserNotificationModelFactory userNotificationModelFactory, IPdfFileService pdfFileService,
            INotificationService notificationService)
        {
            _unitOfWork = unitOfWork;
            _logService = logService;
            _settings = settings;
            _clock = clock;
            _jobEstimateServicesRepository = _unitOfWork.Repository<JobEstimateServices>();
            _jobEstimateImageRepository = _unitOfWork.Repository<JobEstimateImage>();
            _notificationModelFactory = notificationModelFactory;
            _userNotificationModelFactory = userNotificationModelFactory;
            _markbeforeAfterImagesHistryRepository = _unitOfWork.Repository<MarkbeforeAfterImagesHistry>();
            _pdfFileService = pdfFileService;
            _fileRepository = _unitOfWork.Repository<Application.Domain.File>();
            _notificationService = notificationService;
        }

        public void ProcessRecords()
        {
            try
            {
                _logService.Info("Review Marketing Email Job Started");

                var (startDate, endDate) = GetDateRangeForSaturday();

                var utcDate = DateTime.Now.Date;
                var yesterdayDate = _clock.ToUtc(utcDate).AddDays(-7);
                utcDate = utcDate.AddDays(1);
                var todayDate = _clock.ToUtc(utcDate);

                var jobEstimateImageDomain = _jobEstimateImageRepository.Table.ToList();
                var jobEstimateServices = _jobEstimateServicesRepository.Table.Where(x => x.JobEstimateImageCategory != null
                                                                 && x.PairId != null).Select(x => x.Id).ToList();
                todayDate = todayDate.AddDays(1);
                var jobEstimateImageList = jobEstimateImageDomain.Where(x => jobEstimateServices.Contains(x.ServiceId.GetValueOrDefault())
                        && x.IsBestImage && x.BestFitMarkDateTime >= startDate
                                                && x.BestFitMarkDateTime <= endDate).ToList();
                todayDate = todayDate.AddDays(-1);

                if (!_settings.AutoGeneratedMailForBestFitEnabled)
                {
                    _logService.Debug("Auto Generated Mail Best Fit is disabled");
                    return;
                }
                else
                {
                    _logService.Info(string.Format("Starting Auto Generated Mail Best Fit"));

                    _logService.Info("Auto Generated Mail Best Fit Started at- " + _clock.UtcNow);
                    _logService.Info("Auto Generated Mail Best Fit Started from: " + startDate + "To: " + endDate);

                    SendBestFitImages(startDate, endDate, jobEstimateImageList, jobEstimateImageDomain, true,
                        BeforeAfterBestPairType.BESTPAIRMARK, NotificationTypes.BeforeAfterBestPairMail);
                }

                var serviceIds = _markbeforeAfterImagesHistryRepository.Table.Select(x => x.ServiceId).ToList();

                jobEstimateServices = _jobEstimateServicesRepository.Table.Where(x => x.JobEstimateImageCategory != null
                                                                && x.PairId != null && serviceIds.Contains(x.Id)).Select(x => x.Id).ToList();

                todayDate = todayDate.AddDays(1);
                jobEstimateImageList = jobEstimateImageDomain.Where(x => jobEstimateServices.Contains(x.ServiceId.GetValueOrDefault())
                       && x.IsAddToLocalGallery && x.AddToGalleryDateTime >= yesterdayDate
                                               && x.AddToGalleryDateTime <= todayDate).ToList();
                todayDate = todayDate.AddDays(-1);
                if (!_settings.LocalSiteGalleryEnabled)
                {
                    _logService.Debug("Local Site Gallery Image Mail is disabled");
                    return;
                }
                else
                {
                    _logService.Info(string.Format("Starting Local Site Gallery Image Mail"));

                    _logService.Info("Local Site Gallery Image Mail Started at- " + _clock.UtcNow);

                    //SendBestFitImages(yesterdayDate, todayDate, jobEstimateImageList, jobEstimateImageDomain, false,
                    //    BeforeAfterBestPairType.ADDTOLOCALGALLERY, NotificationTypes.LOCALSITEIMAGEGALLERY);
                }
                _logService.Info("Review Marketing Email Job End");
            }
            catch(Exception ex)
            {
                _logService.Error("Error in review Marketing Email" + ex);
            }
        }


        private void SendBestFitImages(DateTime yesterdayDate, DateTime todayDate, List<JobEstimateImage> jobEstimateImageList,
            List<JobEstimateImage> jobEstimateImageDomain, bool isFromBestFit, BeforeAfterBestPairType beforeAfterBestPairType,
            NotificationTypes notificationType)
        {
            try
            {
                var templateName = "";
                var fileName = "";
                var emailId = "";

                var jobIdList = new List<long?>();
                var estimateIdList = new List<long?>();


                var beforeAfterBestPairList = new BeforeAfterBestPairListModel();
                var beforeAfterBestGroupedViewData = new List<BeforeAfterBestPairGroupedViewModel>();
                var beforeAfterBestGroupedListData = new BeforeAfterBestPairGroupedListModel();



                if (jobEstimateImageList.Count() == 0)
                {
                    return;
                }
                foreach (var jobEstimateImage in jobEstimateImageList)
                {

                    var jobEstimateServiceBefore = _jobEstimateServicesRepository.Table.FirstOrDefault(x => x.Id == jobEstimateImage.ServiceId);
                    if (jobEstimateServiceBefore.PairId == null)
                        continue;

                    var jobEstimateImageAfter = jobEstimateImageDomain.FirstOrDefault(x => x.ServiceId == jobEstimateServiceBefore.PairId);
                    var jobEstimateImageBefore = jobEstimateImageDomain.FirstOrDefault(x => x.ServiceId == jobEstimateServiceBefore.Id);
                    var markBeforeAfterImage = _markbeforeAfterImagesHistryRepository.Table.Where(x => x.CategoryId == (long)beforeAfterBestPairType).FirstOrDefault(x => x.ServiceId == jobEstimateServiceBefore.Id);
                    beforeAfterBestPairList.BeforeAfterBestPairViewModel.Add(_userNotificationModelFactory.CreateBeforeAfterBestPairModel(jobEstimateImageBefore, jobEstimateImageAfter, jobEstimateServiceBefore.JobEstimateImageCategory.JobScheduler,
                                         markBeforeAfterImage != null ? markBeforeAfterImage : null));
                }

                beforeAfterBestGroupedViewData = beforeAfterBestPairList.BeforeAfterBestPairViewModel.GroupBy(x => x.FranchiseeName).Select(x => new BeforeAfterBestPairGroupedViewModel
                {
                    FranchiseeName = x.Key,
                    BeforeAfterBestPairViewModel = x.ToList()
                }).ToList();

                if (beforeAfterBestGroupedViewData.Count() == 0)
                {
                    return;
                }
                beforeAfterBestGroupedListData.BeforeAfterBestPairGroupedViewModel.AddRange(beforeAfterBestGroupedViewData);
                if (isFromBestFit)
                {
                    templateName = "before-after-best-pair.cshtml";
                    fileName = "Before_After_Best_Pair_" + DateTime.Now.ToFileTimeUtc() + ".pdf";
                }
                else
                {
                    templateName = "local-site-galary-pair.cshtml";
                    fileName = "Local-Site-Gallery-Pair" + DateTime.Now.ToFileTimeUtc() + ".pdf";

                }

                var destinationFolder = MediaLocationHelper.GetAttachmentMediaLocation().Path + "\\";
                var path = System.Web.Hosting.HostingEnvironment.MapPath(@"~\Templates\");
                var viewPath = destinationFolder + "Templates\\" + templateName;
                var file = _pdfFileService.GeneratePdfFromTemplateAndModel(beforeAfterBestGroupedListData, destinationFolder, fileName, viewPath);
                var fileDomain = GetFileModel(file);
                var model = new BeforeAfterBestPairNotificationModel(_notificationModelFactory.CreateBaseDefault())
                {
                    DateTimes = yesterdayDate.Date.ToString("MM/dd/yyyy"),
                    AssigneePhone = _settings.OwnerPhone,
                    StartDate = yesterdayDate.ToString("MM-dd-yyyy"),
                    EndDate = todayDate.ToString("MM-dd-yyyy"),
                    NavigationUrl = _settings.SiteRootUrl + "#/scheduler/beforeAfter/bestFitMark"

                };

                var currentDate = _clock.UtcNow;

                if (isFromBestFit)
                {
                    emailId = _settings.BeforeAfterRecipientsTo;
                }
                else
                {
                    emailId = _settings.BeforeAfterRecipientsCc;
                }
                var resource = new NotificationResource { Resource = fileDomain, ResourceId = fileDomain.Id, IsNew = true };
                _notificationService.QueueUpNotificationEmail(notificationType, model, _settings.CompanyName, _settings.FromEmail, emailId, _clock.UtcNow, null, new List<NotificationResource> { resource });
                _unitOfWork.SaveChanges();
            }
            catch (Exception ex)
            {
                _logService.Error("Error in Review Marketing Email function SendBestFitImages: " + ex);
            }
        }
        private Application.Domain.File GetFileModel(string localFileName)
        {

            var fileModel = new FileModel
            {
                Name = Path.GetFileName(localFileName),
                Caption = Path.GetFileNameWithoutExtension(localFileName),
                RelativeLocation = Path.GetDirectoryName(localFileName),
                MimeType = "application/pdf",
                Size = new FileInfo(localFileName).Length,
                Extension = Path.GetExtension(localFileName)
            };
            var file = new Application.Domain.File
            {
                Name = fileModel.Name,
                Caption = fileModel.Caption,
                RelativeLocation = fileModel.RelativeLocation,
                MimeType = fileModel.MimeType,
                Size = fileModel.Size,
                IsNew = true,
                DataRecorderMetaData = fileModel.DataRecorderMetaData
            };

            _fileRepository.Save(file);
            return file;
        }

        public static (DateTime startDate, DateTime endDate) GetDateRangeForSaturday()
        {
            DateTime today = DateTime.Today;
            DateTime currentSaturday = today.AddDays(-(int)today.DayOfWeek + (int)DayOfWeek.Saturday);
            if (today.DayOfWeek == DayOfWeek.Sunday)
                currentSaturday = today.AddDays(-1);

            DateTime startDate = currentSaturday.AddDays(-14);
            DateTime endDate = currentSaturday.AddDays(-8);

            return (startDate, endDate);
        }
    }

}