
namespace Core.Notification.Enum
{
    public enum NotificationTypes
    {
        ForgetPassword = 1,
        SendLoginCredential = 2,
        SendInvoiceDetail = 3,
        PaymentReminder = 4,
        SalesDataUploadReminder = 5,
        LateFeeReminderForPayment = 6,
        PaymentConfirmation = 7,
        LateFeeReminderForSalesData = 8,
        WeeklyLateFeeNotification = 9,
        WeeklyUnpaidInvoiceNotification = 10,
        CustomerFeedbackRequest = 11,
        ListCustomerMonthlyNotification = 12,
        MonthlyReviewNotification = 13,
        MonthlyMailChimpReport = 14,
        MonthlySalesUploadNotification = 15,
        AnnualUploadFailNotification = 16,
        AnnualUploadParsedNotification = 17,
        AnnualUploadNotificationToAdmin = 18,
        AnnualUploadApproved = 19,
        AnnualUploadRejected = 20,
        SendLoginCredentialWithSetupGuide = 21,
        DocumentUploadNotification = 22,
        DocumentExpiryNotification = 23,
        DocumentUploadNotificationToFranchisee = 24,
        NewJobNotificationToUser=25,
        NewJobNotificationToTech = 26,
        CancleJobNotificationToTech = 27,
        UpdateJobNotificationToTech = 28,
        PostEstimatetoCustomer = 29,
        NewJobNotificationToUserOnDay = 30,
        NewJobNotificationToUserReassigned = 31,
        UrgentJobNotificationToUser = 32,
        ArReportNotification = 33,
        BeforeAfterImages=34,
        InvoiceImages = 35,
        FranchiseeLoanCompletion = 36,
        NewCustomerMail=37,
        UpdateCustomerMail=38,
        BeforeAfterBestPairMail=39,
        LOCALSITEIMAGEGALLERY = 40,
        NonResidentalBuildingMail = 41,
        BeforeAfterImageForFA=42,
        NotificationToFA=43,
        RenewableMailForFranchiseeBefore9Month=44,
        RenewableMailForFranchiseeBefore8Month = 45,
        MeetingMailForMemebers = 46,
        PersonalMailForMemebers = 47,
        DeletionJobNotificationToTech=48,
        MailToFranchiseeAdminForRPID=49,
        MailToCustomerForInvoice = 50,
        MailToCustomerForSignedInvoice = 51,
        MailToSalesRepForSignedInvoice = 52,
        MailToCustomerForPostJobCompletion = 53,
        PostJobFeedbackToCustomer = 54,
        PostJobFeedbackToSalesRep = 55,
        PostJobFeedbackToAdmin = 56,
        WebLeadsMail = 57,
        NotificationToSuperAdminIfFranchiseePriceExceedsTheBulkCorporatePrice =58,
        SendLinkToFranchiseeOwnerAndSchedulerForPayrollReport = 59,
        SendLinkToSalesRepAndTechnicianForPayrollReport = 60,
        PhotoReportEmailToFranchiseeOwnerAndScheduler = 61,
        PhotoReportEmailToSalesRepandTechnician = 62,
        WeeklyNotificationOfPhotoManagement = 63
    }
}
