//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Localization.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Localization.Validations.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been canceled..
        /// </summary>
        public static string AccountCanceled {
            get {
                return ResourceManager.GetString("AccountCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification is pending. Please verify your email..
        /// </summary>
        public static string EmailVerification {
            get {
                return ResourceManager.GetString("EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Equal Opportunity Housing Agreement..
        /// </summary>
        public static string EqualOpportunityHousingDisclaimer {
            get {
                return ResourceManager.GetString("EqualOpportunityHousingDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pin code entered..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password. Please try again..
        /// </summary>
        public static string InvalidCredentials1 {
            get {
                return ResourceManager.GetString("InvalidCredentials1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password. You have got 2 more attempts left before your account gets locked. Please use carefully..
        /// </summary>
        public static string InvalidCredentialsLastTwoAttempts {
            get {
                return ResourceManager.GetString("InvalidCredentialsLastTwoAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strengthInBits must be evenly divisible by 8..
        /// </summary>
        public static string InvalidStrengthBitsLength {
            get {
                return ResourceManager.GetString("InvalidStrengthBitsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or email id does not exist our records..
        /// </summary>
        public static string InvalidUserNameEmailNotInRecords {
            get {
                return ResourceManager.GetString("InvalidUserNameEmailNotInRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string MustMatch {
            get {
                return ResourceManager.GetString("MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t choose same password again.
        /// </summary>
        public static string PasswordRepeatation {
            get {
                return ResourceManager.GetString("PasswordRepeatation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code entered is expired. Please request for a new code..
        /// </summary>
        public static string PincodeExpire {
            get {
                return ResourceManager.GetString("PincodeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Privacy Policy to proceed..
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a special character,numerical, lower case and upper case character.
        /// </summary>
        public static string StrongPassword {
            get {
                return ResourceManager.GetString("StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Terms &amp; Conditions to proceed..
        /// </summary>
        public static string TermsCondition {
            get {
                return ResourceManager.GetString("TermsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorize access..
        /// </summary>
        public static string UnauthorizeUser {
            get {
                return ResourceManager.GetString("UnauthorizeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string UniqueUserName {
            get {
                return ResourceManager.GetString("UniqueUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deactivated, please contact admin..
        /// </summary>
        public static string UserDeactivated {
            get {
                return ResourceManager.GetString("UserDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not activated, Check your email for activate link..
        /// </summary>
        public static string UserNotActivated {
            get {
                return ResourceManager.GetString("UserNotActivated", resourceCulture);
            }
        }
        public static string InvalidCodeForCustomer
        {
            get
            {
                return ResourceManager.GetString("InvalidCodeForCustomer", resourceCulture);
            }
        }

        public static string CodeExpired
        {
            get
            {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
    }
}
